#!/usr/bin/env python3

count = 0

with open("dracula.txt", "r") as dracula:
    with open("vampytimes.txt", "w") as vampfile:
        for line in dracula:
            if "vampire" in line.lower():
#                print(line)
                count = count + 1
                vampfile.write(line)
#                print(line, file=vampfile)

